on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.5

      - name: Set up Google Cloud credentials
        run: echo "$GCP_SA_KEY" > "$HOME"/gcp_credentials.json
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

      - name: Terraform Init and Apply
        run: |
          terraform init
          terraform apply -auto-approve
