on: push
jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TF_VAR_gcp_credentials_file: gcp_credentials.json
      TF_VAR_project_id: celestial-opus-418317
      TF_VAR_region: europe-central2
      TF_LOG: INFO
      TF_INPUT: false

    steps:
      - uses: actions/checkout@v2

      - name: Setup GCP Credentials
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > "${{ env.TF_VAR_gcp_credentials_file }}"
        shell: bash

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.5

      - name: Terraform Init and Apply
        run: |
          terraform init  
          terraform apply -auto-approve
