on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TF_VAR_gcp_credentials_file: gcp_credentials.json
      TF_VAR_project_id: celestial-opus-418317
      TF_VAR_region: europe-central2

    steps:
      - uses: actions/checkout@v2

      - name: Setup GCP Credentials
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > "${{ env.TF_VAR_gcp_credentials_file }}"
        shell: bash

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        uses: hashicorp/terraform-github-actions/init@v0.4.0

      - name: Terraform Apply
        uses: hashicorp/terraform-github-actions/apply@v0.4.0
